# Generated by Django 5.0 on 2023-12-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_parent',
            new_name='parent',
        ),
    ]
