# Generated by Django 5.0 on 2023-12-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_rename_item_parent_item_parent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='MenuItem',
        ),
    ]
